steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/my-repository/myimage:${SHORT_SHA}', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/my-repository/myimage:${SHORT_SHA}']

images:
  - us-central1-docker.pkg.dev/${PROJECT_ID}/my-repository/myimage:${SHORT_SHA}
# [END cloudbuild_python_yaml]
options:
  logging: CLOUD_LOGGING_ONLY